package directive

import (
	"go/ast"
	"go/parser"
	"go/token"
	"slices"
	"testing"

	"github.com/mpyw/molint/internal/rule"
)

// scanSource parses src as file name, and scans its directives.
func scanSource(t *testing.T, name, src string) (*token.FileSet, *ast.File, *Set) {
	t.Helper()
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, name, src, parser.ParseComments)
	if err != nil {
		t.Fatal(err)
	}
	read := func(string) ([]byte, error) { return []byte(src), nil }
	return fset, f, Scan(fset, []*ast.File{f}, read)
}

// lineStart is the position of the start of line in f.
func lineStart(fset *token.FileSet, f *ast.File, line int) token.Pos {
	return fset.File(f.Pos()).LineStart(line)
}

func allOn(rule.Name) bool { return true }

// A reason cannot be pinned by the analysistest fixtures: the expectation
// comment on a directive's line would be read as its reason.
func TestScanReason(t *testing.T) {
	const src = `package p

func f() {
	//molint:ignore
	_ = 0
	//molint:ignore //
	_ = 1
	//molint:ignore return-nil
	_ = 2
	//molint:ignore // reason
	_ = 3
	//molint:ignore//reason
	_ = 4
}
`
	fset, f, s := scanSource(t, "p.go", src)
	var lines []int
	for _, p := range s.Problems() {
		if p.Message != "molint:ignore needs a reason after //" {
			t.Errorf("problem %q", p.Message)
		}
		lines = append(lines, fset.Position(p.Pos).Line)
	}
	if !slices.Equal(lines, []int{4, 6, 8}) {
		t.Errorf("problems on lines %v, want [4 6 8]", lines)
	}
	// An ignore without a reason silences nothing.
	for line, want := range map[int]bool{5: false, 7: false, 9: false, 11: true, 13: true} {
		if got := s.Ignored(lineStart(fset, f, line), rule.ReturnNil); got != want {
			t.Errorf("Ignored(line %d) = %v, want %v", line, got, want)
		}
	}
	if u := s.Unused(allOn); len(u) != 0 {
		t.Errorf("Unused() = %v, want none", u)
	}
}

func TestScanPlacement(t *testing.T) {
	const src = `package p

func f() {
	_ = 0 //molint:ignore return-nil // trailing
	_ = 1
	//molint:ignore return-bool // own line
	_ = 2
}
`
	fset, f, s := scanSource(t, "p.go", src)
	cases := []struct {
		line int
		r    rule.Name
		want bool
	}{
		{4, rule.ReturnNil, true},
		{5, rule.ReturnNil, false},
		{6, rule.ReturnBool, false},
		{7, rule.ReturnBool, true},
		{7, rule.ReturnNil, false},
	}
	for _, c := range cases {
		if got := s.Ignored(lineStart(fset, f, c.line), c.r); got != c.want {
			t.Errorf("Ignored(line %d, %s) = %v, want %v", c.line, c.r, got, c.want)
		}
	}
}

func TestUnusedWhenOff(t *testing.T) {
	const src = `package p

//molint:ignore return-error // off by default
func f() {}

//molint:ignore return-error, return-nil // one of them is on
func g() {}
`
	fset, _, s := scanSource(t, "p.go", src)
	on := func(r rule.Name) bool { return r != rule.ReturnError }
	var lines []int
	for _, pos := range s.Unused(on) {
		lines = append(lines, fset.Position(pos).Line)
	}
	if !slices.Equal(lines, []int{6}) {
		t.Errorf("unused on lines %v, want [6]", lines)
	}
}

func TestScanGenerated(t *testing.T) {
	const src = `// Code generated by hand. DO NOT EDIT.

package p

//molint:ignore
//molint:unknown
var _ = 0
`
	fset, f, s := scanSource(t, "gen.go", src)
	if len(s.Problems()) != 0 || len(s.Unused(allOn)) != 0 || s.Ignored(lineStart(fset, f, 7), rule.ReturnNil) {
		t.Errorf("a generated file was read: %v, %v", s.Problems(), s.Unused(allOn))
	}
}

// A file that cgo rewrote carries the generated marker, but its code and its
// directives are the user's.
func TestScanCgo(t *testing.T) {
	const src = `// Code generated by cmd/cgo; DO NOT EDIT.

package p

//molint:ignore // intended
var _ = 0
`
	fset, f, s := scanSource(t, "p.cgo1.go", src)
	if Generated(f) {
		t.Error("a file cgo rewrote counts as generated")
	}
	if !s.Ignored(lineStart(fset, f, 6), rule.ReturnNil) {
		t.Error("the directive in a file cgo rewrote was not read")
	}
}

func TestOnOwnLinePastEnd(t *testing.T) {
	if !onOwnLine([]byte("x"), 10) {
		t.Error("an offset past the text counts as a line of its own")
	}
}
