package directive

import (
	"go/ast"
	"go/parser"
	"go/token"
	"testing"
)

// parseSource parses src as file name, with its comments.
func parseSource(t *testing.T, fset *token.FileSet, name, src string) *ast.File {
	t.Helper()
	f, err := parser.ParseFile(fset, name, src, parser.ParseComments)
	if err != nil {
		t.Fatal(err)
	}
	return f
}

// lineStart is the position of the start of line in f.
func lineStart(fset *token.FileSet, f *ast.File, line int) token.Pos {
	return fset.File(f.Pos()).LineStart(line)
}

func TestScan(t *testing.T) {
	const src = `package p

func f() {
	//molint:ignore
	_ = 0
	//molint:ignore //
	_ = 1
	//molint:ignore // reason
	_ = 2
	//molint:ignore//reason
	_ = 3
	_ = 4 //molint:ignore // same line
}
`
	fset := token.NewFileSet()
	f := parseSource(t, fset, "p.go", src)
	s := Scan(fset, []*ast.File{f})

	var lines []int
	for _, p := range s.Problems() {
		if p.Message != "molint:ignore needs a reason after //" {
			t.Errorf("problem %q", p.Message)
		}
		lines = append(lines, fset.Position(p.Pos).Line)
	}
	if len(lines) != 2 || lines[0] != 4 || lines[1] != 6 {
		t.Errorf("problems on lines %v, want [4 6]", lines)
	}
	for line, want := range map[int]bool{5: false, 7: false, 9: true, 11: true, 12: true} {
		if got := s.Ignored(lineStart(fset, f, line)); got != want {
			t.Errorf("Ignored(line %d) = %v, want %v", line, got, want)
		}
	}
	if u := s.Unused(); len(u) != 0 {
		t.Errorf("Unused() = %v, want none", u)
	}
}

func TestScanGenerated(t *testing.T) {
	const src = `// Code generated by hand. DO NOT EDIT.

package p

//molint:ignore
//molint:unknown
var _ = 0
`
	fset := token.NewFileSet()
	f := parseSource(t, fset, "gen.go", src)
	s := Scan(fset, []*ast.File{f})
	if len(s.Problems()) != 0 || len(s.Unused()) != 0 || s.Ignored(lineStart(fset, f, 7)) {
		t.Errorf("a generated file was read: %v, %v", s.Problems(), s.Unused())
	}
}
