// Code generated by hand for the molint fixtures. DO NOT EDIT.

package fieldnilcompare

// Gen is declared in a generated file, so its fields are not looked at.
type Gen struct {
	P *T
}

// GenCompare is in a generated file, so nothing is reported here.
func GenCompare(s *S) bool {
	return s.P == nil
}
